name: Hello World Workflow

# This workflow is triggered on pushes to the repository.
on: [push]

jobs:
  hello_world_job:
    runs-on: self-hosted
    steps:
      - name: Print Hello World.
        run: echo "Hello world"