name: work
run-name: ${{ github.actor }} is doing part 3
on:
  push:
    branches: [ "master" ] 

jobs:
  check-bats-version:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run all the tests
        run: make test
